---
driver:
  name: vagrant
provisioner:
  name: chef_solo
platforms:
  - name: centos-7.0
suites:
  - name: default
    attributes:
      maven_deploy:
        repositories:
          central: "https://repo1.maven.org/maven2"
    run_list:
      - "recipe[maven_deploy_test]"

  - name: no_repository_data
    attributes:
      maven_deploy:
        repositories:
          central:
            snapshots:
              url: "https://repo1.maven.org/maven2"
    run_list:
      - "recipe[maven_deploy_test::no_repository_data]"
