name             'maven_deploy'
maintainer       'Alexander De Leon'
maintainer_email 'me@alexdeleon.name'
license          'MIT'
description      'Dowloads artifacts from standard maven repositories'
long_description 'Dowloads artifacts from standard maven repositories'
version          '0.1.0'
