name             'maven_deploy'
maintainer       'Alexander De Leon'
maintainer_email 'me@alexdeleon.name'
license          'MIT'
description      'Deploy artifacts from maven'
long_description 'Downloads artifacts from standard maven repositories'
version          '0.2.0'
